language: c
sudo: false

branches:
  only:
    - master

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
  - os: osx
    compiler: clang

script:
  - autoreconf -i
  - ./configure
  - make V=1
  - make test
