language: c
sudo: false

branches:
  only:
    - master

matrix:
  include:
  - os: linux
    compiler: clang
  - os: linux
    compiler: gcc
  - os: osx
    compiler: clang

before_install:
  - if [ $TRAVIS_OS_NAME == osx ] ; then brew install nss || true ; fi

script:
  - autoreconf -i
  - ./configure
  - make V=1
  - make test
